pipeline:
  file: /pipelines/default.json
auth:
  provider: NONE
valkey:
  dsn: redis://resilmesh-redis:6379/4
  ssl: False
context:
  mysql:
    dsn: mysql://root:root@context-mysql:3306/
    database: Anonymizer
services:
  arxlet:
    url: http://resilmesh-tap-ppcti-arxlet:8080/api
  flaskdp:
    url: http://resilmesh-tap-ppcti-flaskdp:8000
  misp:
    url: https://ants-misp.inf.um.es/users/login
    key: Azije0YdpPAFRBrv1wT3XuQCBf9DnqUXlWkCMGKi
    ssl: true
