pipeline:
  file: /pipelines/default.json
auth:
  provider: NONE
valkey:
  dsn: redis://resilmesh-redis:6379/4
  ssl: False
context:
  mysql:
    dsn: mysql://root:root@context-mysql:3306/
    database: Anonymizer
services:
  arxlet:
    url: http://resilmesh-tap-ppcti-arxlet:8080/api
  flaskdp:
    url: http://resilmesh-tap-ppcti-flaskdp:8000
  misp:
    url: https://Resilmesh-MISP
    key: 8wmyg8sKMgqi1lnrvT5kYrbs6VMYKit7r9bHG0D8
    ssl: false
