services:
  flaskdp:
    build:
      context: .
    container_name: resilmesh-tap-ppcti-flaskdp
    hostname: resilmesh-tap-ppcti-flaskdp
    expose:
      - 8000
    networks:
      - resilmesh_network
