services:
  flaskdp:
    build:
      context: .
    container_name: resilmesh_tap_ppcti_flaskdp
    hostname: resilmesh_tap_ppcti_flaskdp
    expose:
      - 8000
    networks:
      - resilmesh_network
